version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: